# SOME DESCRIPTIVE TITLE.
# Copyright (C)
# This file is distributed under the same license as the Algolib package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Algolib \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-08-16 04:41+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: zh_CN\n"
"Language-Team: zh_CN <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: ../source/api/algolib.rst:2
msgid "algolib package"
msgstr "algolib 包"

#: ../source/api/algolib.rst:5
msgid "Subpackages"
msgstr "子包"

#: ../source/api/algolib.rst:13
msgid "Submodules"
msgstr "子模块"

#: ../source/api/algolib.rst:16
msgid "algolib.exceptions module"
msgstr "algolib.exceptions 模块"

#: algolib.exceptions.AlgolibError:1 of
msgid "Bases: :py:class:`Exception`"
msgstr "基类：:py:class:`Exception`"

#: algolib.exceptions.AlgolibError:1 of
msgid "Base exception for this library."
msgstr "此库的基础异常类。"

#: algolib.exceptions.InvalidTypeError:1 of
msgid "Bases: :py:class:`~algolib.exceptions.AlgolibError`, :py:class:`TypeError`"
msgstr "基类：:py:class:`~algolib.exceptions.AlgolibError`, :py:class:`TypeError`"

#: algolib.exceptions.InvalidTypeError:1 of
msgid "Raised when an argument has an invalid type."
msgstr "当参数类型无效时引发。"

#: algolib.exceptions.InvalidValueError:1 of
msgid ""
"Bases: :py:class:`~algolib.exceptions.AlgolibError`, "
":py:class:`ValueError`"
msgstr "基类：:py:class:`~algolib.exceptions.AlgolibError`, :py:class:`ValueError`"

#: algolib.exceptions.InvalidValueError:1 of
msgid "Raised when an argument has an invalid value."
msgstr "当参数值无效时引发。"

#: ../source/api/algolib.rst:24
msgid "algolib.sample module"
msgstr "algolib.sample 模块"

#: algolib.sample.add:1 of
msgid "Return a + b."
msgstr "返回 a + b。"

#: ../source/api/algolib.rst:32
msgid "Module contents"
msgstr "模块内容"

